### ISSUE TITLE
Engine name

### ISSUE THREAD

**Issue by amanjpro** [paulolemus/blunders#2]
Hey, just to let you know that there is already an engine named Blunder, which might make your engine's name confusing (and easy to mix with the other).

https://github.com/algerbrex/blunder

**Comment by paulolemus** [comment]
Hello, thanks for the heads up, its a funny coincidence! I reached out to the developer and so far neither of us are concerned. I am open to changing the name around 1.0 release however if it ends up being too confusing or if I find a good alternative name.

**Comment by amanjpro** [comment]
Cool then, closing the issue if you don't mind
